### ISSUE TITLE
README Elaboration

### ISSUE THREAD

**Issue by Pandakar** [cscw2015/maverick#1]
The current **README** file is bland and does nothing. We should add an abstract of our project here as well as our group members and their roles.

**Comment by cscw2015** [comment]
I just started a new issue with the group roles. Once we have these established, I agree we should add them to the README. As for the abstract of our project, what about:

Group Maverick is conducting a study of Victoria City Council and their communications, particularly with respect to technology. We will interview city councillors and/or the mayor of Victoria to determine what their current technology practices are, and write a consultant's report to council of our findings, including recommendations for communications software they may choose to adopt in future. Our proposed approach is to conduct qualitative, semi-structured individual interviews to determine trends and collect data. Then we will analyze this data collectively using coding to determine themes in the answers of the respondents. This study is being conducted under the auspices of Dr. Storey at the University of Victoria, Canada, in partial fulfillment of the requirements for a course in Computer Supported Collaborative Work.

**Comment by Pandakar** [comment]
Not sure what you mean by "analyze this data collectively using coding." We also don't mention what we're going to do with this information afterwards, which is equally as important. We could change this sentence to start as "After analysis of this data, we will be providing **x** to the city council of Victoria" with whatever we decide **x** to be.

**Comment by cscw2015** [comment]
Ok, as for the coding thing, I watched a video today (which I posted in Slack), and it said the way you analyze qualitative data is by marking what you think is important, then organizing into themes, also known as "coding." But you're right, I guess that is just confusing for a quick overview. How about this:

Group Maverick is conducting a study of Victoria City Council and their communications, particularly with respect to technology. We will interview city councillors and/or the mayor of Victoria to determine what their current technology practices are, and write a consultant's report to council of our findings, including recommendations for communications software they may choose to adopt in future. Our proposed approach is to conduct qualitative, semi-structured individual interviews to determine trends and collect data. Then we will analyze this data collectively to determine themes in the answers of the respondents. After analysis of this data, we will be providing a consultant's report to the city of Victoria about software they might consider using, along with costs of the software. This study is being conducted under the auspices of Dr. Storey at the University of Victoria, Canada, in partial fulfillment of the requirements for a course in Computer Supported Collaborative Work.

**Comment by Pandakar** [comment]
Seems fine for an abstract for now. Maybe we can revisit it later when we're finishing up the interim report. Closing this issue as [the issue you opened](https://github.com/cscw2015/maverick/issues/3) addresses the other half of the concerns I had regarding the README.
