### ISSUE TITLE
Task division (roles)

### ISSUE THREAD

**Issue by cscw2015** [cscw2015/maverick#3]
Hi all,

I took a stab at dividing up roles based on tasks we need to accomplish.  Please take a look at the document and let me know if you agree with the proposed task division, or feel free to amend it. I thought the best way would be to put different people in charge of different parts of the process, with an emphasis still on collaboration.
[CSCW--Group Maverick Roles.txt](https://github.com/cscw2015/maverick/files/24798/CSCW--Group.Maverick.Roles.txt)

**Comment by Pandakar** [comment]
The main gist of what I'm reading from your proposed division of work is 5 distinct roles with no overlap between them. Is that right? If so, I'm not sure our project is complex enough to warrant this type of specialization. Namely, I don't think a 1:1 relation between member and role type is the answer; we can have people performing similar roles in a project.  

Rough thoughts on this breakdown:
- for head data collector to ensure interviews are transcribed, they'd have to go over the transcriptions alongside the audio file; if intention is to dedicate 1.5-2h of work per interview file (1h for initial transcription and 0.5h-1h for verification) then it seems fine on its own. Will most likely result in a heavier workload in comparison to other proposed roles
- Data Analyzer role seems to be very vague. Person in role won't end up doing much of anything? _if_ we keep this role title, need to expand on it somehow
- Report Writer role could re-named as Editor or similar term to better emphasize the work involved
- Presentation Giver sees similar issues as Analyzer role: doesn't do much of anything to warrant a distinct split of labor

I'll give this a bit more thought and see if I can't come up with a better way to distinguish between the roles each member has to conduct.

**Comment by ndufty** [comment]
I feel like part of the problem is that Peggy wants group roles for everyone, but the way or project works and how we have been working as a group hasn't been in a way that relies on individuals working each having specific roles.

**Comment by Pandakar** [comment]
Group roles have been defined and put into the interim report.
